patterns = {
    '2crows': 'Two Crows',
    '3blackcrows': 'Three Black Crows', 
    '3inside': 'Three Inside Up/Down', 
    '3linestrike': 'Three-Line Strike', 
    '3outside': 'Three Outside Up/Down', 
    '3starsinsouth': 'Three Stars In The South', 
    '3whitesoldiers': 'Three Advancing White Soldiers', 
    'abandonedbaby': 'Abandoned Baby', 
    'advanceblock': 'Advance Block', 
    'belthold': 'Belt-hold', 
    'breakaway': 'Breakaway', 
    'closingmarubozu': 'Closing Marubozu', 
    'concealbabyswall': 'Concealing Baby Swallow', 
    'counterattack': 'Counterattack', 
    'darkcloudcover': 'Dark Cloud Cover', 
    'doji': 'Doji', 
    'dojistar': 'Doji Star', 
    'dragonflydoji': 'Dragonfly Doji', 
    'engulfing': 'Engulfing Pattern', 
    'eveningdojistar': 'Evening Doji Star', 
    'eveningstar': 'Evening Star', 
    'gapsidesidewhite': 'Up/Down-gap side-by-side white lines', 
    'gravestonedoji': 'Gravestone Doji', 
    'hammer': 'Hammer', 
    'hangingman': 'Hanging Man', 
    'harami': 'Harami Pattern', 
    'haramicross': 'Harami Cross Pattern', 
    'highwave': 'High-Wave Candle', 
    'hikkake': 'Hikkake Pattern', 
    'hikkakemod': 'Modified Hikkake Pattern', 
    'homingpigeon': 'Homing Pigeon', 
    'identical3crows': 'Identical Three Crows', 
    'inneck': 'In-Neck Pattern', 
    'invertedhammer': 'Inverted Hammer', 
    'kicking': 'Kicking', 
    'kickingbylength': 'Kicking - bull/bear determined by the longer marubozu', 
    'ladderbottom': 'Ladder Bottom', 
    'longleggeddoji': 'Long Legged Doji', 
    'longline': 'Long Line Candle', 
    'marubozu': 'Marubozu', 
    'matchinglow': 'Matching Low', 
    'mathold': 'Mat Hold', 
    'morningdojistar': 'Morning Doji Star', 
    'morningstar': 'Morning Star', 
    'onneck': 'On-Neck Pattern', 
    'piercing': 'Piercing Pattern', 
    'rickshawman': 'Rickshaw Man', 
    'risefall3methods': 'Rising/Falling Three Methods', 
    'separatinglines': 'Separating Lines', 
    'shootingstar': 'Shooting Star', 
    'shortline': 'Short Line Candle', 
    'spinningtop': 'Spinning Top', 
    'stalledpattern': 'Stalled Pattern', 
    'sticksandwich': 'Stick Sandwich', 
    'takuri': 'Takuri (Dragonfly Doji with very long lower shadow)', 
    'tasukigap': 'Tasuki Gap', 
    'thrusting': 'Thrusting Pattern', 
    'tristar': 'Tristar Pattern', 
    'unique3river': 'Unique 3 River' , 
    'upsidegap2crows': 'Upside Gap Two Crows', 
    'xsidegap3methods': 'Upside/Downside Gap Three Methods'
}

patterns_value = {
    '2crows': 'CDL_2CROWS',
    '3blackcrows': 'CDL_3BLACKCROWS', 
    '3inside': 'CDL_3INSIDE', 
    '3linestrike': 'CDL_3LINESTRIKE', 
    '3outside': 'CDL_3OUTSIDE', 
    '3starsinsouth': 'CDL_3STARSINSOUTH', 
    '3whitesoldiers': 'CDL_3WHITESOLDIERS', 
    'abandonedbaby': 'CDL_ABANDONEDBABY', 
    'advanceblock': 'CDL_ADVANCEBLOCK', 
    'belthold': 'CDL_BELTHOLD', 
    'breakaway': 'CDL_BREAKAWAY', 
    'closingmarubozu': 'CDL_CLOSINGMARUBOZU', 
    'concealbabyswall': 'CDL_CONCEALBABYSWALL', 
    'counterattack': 'CDL_COUNTERATTACK', 
    'darkcloudcover': 'CDL_DARKCLOUDCOVER', 
    'doji': 'CDL_DOJI_10_0.1', 
    'dojistar': 'CDL_DOJISTAR', 
    'dragonflydoji': 'CDL_DRAGONFLYDOJI', 
    'engulfing': 'CDL_ENGULFING', 
    'eveningdojistar': 'CDL_EVENINGDOJISTAR', 
    'eveningstar': 'CDL_EVENINGSTAR', 
    'gapsidesidewhite': 'CDL_GAPSIDESIDEWHITE', 
    'gravestonedoji': 'CDL_GRAVESTONEDOJI', 
    'hammer': 'CDL_HAMMER', 
    'hangingman': 'CDL_HANGINGMAN', 
    'harami': 'CDL_HARAMI', 
    'haramicross': 'CDL_HARAMICROSS', 
    'highwave': 'CDL_HIGHWAVE', 
    'hikkake': 'CDL_HIKKAKE', 
    'hikkakemod': 'CDL_HIKKAKEMOD', 
    'homingpigeon': 'CDL_HOMINGPIGEON', 
    'identical3crows': 'CDL_IDENTICAL3CROWS', 
    'inneck': 'CDL_INNECK', 
    'invertedhammer': 'CDL_INVERTEDHAMMER', 
    'kicking': 'CDL_KICKING', 
    'kickingbylength': 'CDL_KICKINGBYLENGTH', 
    'ladderbottom': 'CDL_LADDERBOTTOM', 
    'longleggeddoji': 'CDL_LONGLEGGEDDOJI', 
    'longline': 'CDL_LONGLINE', 
    'marubozu': 'CDL_MARUBOZU', 
    'matchinglow': 'CDL_MATCHINGLOW', 
    'mathold': 'CDL_MATHOLD', 
    'morningdojistar': 'CDL_MORNINGDOJISTAR', 
    'morningstar': 'CDL_MORNINGSTAR', 
    'onneck': 'CDL_ONNECK', 
    'piercing': 'CDL_PIERCING', 
    'rickshawman': 'CDL_RICKSHAWMAN', 
    'risefall3methods': 'CDL_RISEFALL3METHODS', 
    'separatinglines': 'CDL_SEPARATINGLINES', 
    'shootingstar': 'CDL_SHOOTINGSTAR', 
    'shortline': 'CDL_SHORTLINE', 
    'spinningtop': 'CDL_SPINNINGTOP', 
    'stalledpattern': 'CDL_STALLEDPATTERN', 
    'sticksandwich': 'CDL_STICKSANDWICH', 
    'takuri': 'CDL_TAKURI', 
    'tasukigap': 'CDL_TASUKIGAP', 
    'thrusting': 'CDL_THRUSTING', 
    'tristar': 'CDL_TRISTAR', 
    'unique3river': 'CDL_UNIQUE3RIVER' , 
    'upsidegap2crows': 'CDL_UPSIDEGAP2CROWS', 
    'xsidegap3methods': 'CDL_XSIDEGAP3METHODS'     
}